name: test
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc: ["8.6.5", "8.8.3", "8.10.1"]
        # Newer versions of GHC are broken on Windows:
        # https://gitlab.haskell.org/ghc/ghc/-/issues/17926
        exclude:
          - os: windows-latest
            ghc: "8.8.3"
          - os: windows-latest
            ghc: "8.10.1"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: cabal build all '--build-log=logs/$pkgid' -fbuild-examples
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: logs-${{ matrix.os }}-ghc${{ matrix.ghc }}
          path: logs/
      - run: cabal install byline -fbuild-examples --installdir=artifacts --install-method=copy
      - uses: actions/upload-artifact@v2
        with:
          name: examples-${{ matrix.os }}-ghc${{ matrix.ghc }}
          path: artifacts/
