name: test
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc: ["8.6.5", "8.8.3", "8.10.1"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: cabal build all --verbose=3 -fbuild-examples
      - run: cabal install byline -fbuild-examples --installdir=artifacts --install-method=copy
      - uses: actions/upload-artifact@v2
        with:
          name: examples-${{ matrix.os }}-ghc${{ matrix.ghc }}
          path: artifacts/
